language: cpp
sudo: false
script:
- wget https://github.com/bweir/OpenSpin/releases/download/qt-0.1.0/openspin
- chmod a+x ./openspin
- SPINC=./openspin make -f scripts/makefile -j
- make -f scripts/makefile clean
  RELEASE=${TRAVIS_TAG} ./scripts/release.sh
after_script:
- ls *.zip
- du *.zip
deploy:
  provider: releases
  api_key:
    secure: NEA2RzoKNiT4JL1d6iJFNeZksns5m9AaVT2hA1CljJzhOjUJ7o4zhfyOI0Ev61M5WAKOEyKNQSh4dvXiFr37xuWVNAiSxUIKID2QZ7FMm2933lzxYhztA6HLChb/qSGrHluJmOsxr9Cz3GbaWCPARjbnPMtbl2l5hszykxCAMPo=
  file_glob: true
  file: *.zip
  skip_cleanup: true
  on:
    repo: lamestation/lamestation-sdk
    tags: true
    all_branches: true
