language: cpp
sudo: false
script:
- wget https://github.com/bweir/OpenSpin/releases/download/0.2.2/openspin.linux-gcc.zip
- unzip openspin.linux-gcc.zip
- SPINC=./openspin make -f scripts/makefile -j
- make -f scripts/makefile clean
- git clone https://github.com/lamestation/lamestation-sdk "lamestation-sdk-${TRAVIS_TAG}" --recursive
- echo "lamestation-sdk-${TRAVIS_TAG}"
- zip "lamestation-sdk-${TRAVIS_TAG}.zip" lamestation-sdk-${TRAVIS_TAG}/
after_script:
- ls *.zip
